//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectedServices
    {
        public int ConnectedServiceID { get; set; }
        public int UserID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<int> DatePeriod { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
