//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.PurchasedMovies = new HashSet<PurchasedMovies>();
        }
    
        public int FilmID { get; set; }
        public int GenreID { get; set; }
        public string FilmName { get; set; }
        public string FilmImage { get; set; }
        public string Country { get; set; }
        public string Duration { get; set; }
        public string Mark { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ReleaseYear { get; set; }
        public string Actors { get; set; }
        public string Producers { get; set; }
        public string Director { get; set; }
        public double MoviePrice { get; set; }
    
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedMovies> PurchasedMovies { get; set; }
    }
}
