//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedMovies
    {
        public int PurchasedMovieID { get; set; }
        public int FilmID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PurchasedDate { get; set; }
    
        public virtual Movies Movies { get; set; }
        public virtual Users Users { get; set; }
    }
}
