//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.ConnectedServices = new HashSet<ConnectedServices>();
            this.PurchasedMovies = new HashSet<PurchasedMovies>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public string CardNumber { get; set; }
        public double CardBalance { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserMiddleName { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectedServices> ConnectedServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedMovies> PurchasedMovies { get; set; }
        public virtual Subscritions Subscritions { get; set; }
    }
}
